// Generated by LiveScript 1.2.0
var CoordMapType, main;
CoordMapType = function(it){
  return this.tileSize = it, this;
};
CoordMapType.prototype.getTile = function(coord, zoom, doc){
  var div, x$, y$;
  div = doc.createElement('div');
  x$ = div;
  y$ = x$.style;
  y$.width = this.tileSize.width + "px";
  y$.height = this.tileSize.height + "px";
  y$.opacity = "0.6";
  y$.background = "url(https://raw.githubusercontent.com/zbryikt/tile-cityusage/gh-pages/" + zoom + "/" + coord.x + "/" + coord.y + ".png) center center no-repeat";
  return x$;
};
main = function($scope, $timeout){
  $scope.taipei = new google.maps.LatLng(25.062706, 121.533563);
  $scope.mapOption = {
    zoom: 12,
    minZoom: 12,
    maxZoom: 18,
    center: $scope.taipei
  };
  $scope.isAddrToggled = false;
  $scope.toggleAddr = function(){
    return $scope.isAddrToggled = !$scope.isAddrToggled;
  };
  $scope.init = function(){
    var a;
    $scope.map = new google.maps.Map(document.getElementById('map'), $scope.mapOption);
    a = new CoordMapType(new google.maps.Size(256, 256));
    return $scope.map.overlayMapTypes.insertAt(0, a);
  };
  return google.maps.event.addDomListener(window, 'load', function(){
    return $scope.$apply(function(){
      return $scope.init();
    });
  });
};