// Generated by LiveScript 1.2.0
var main;
main = function($scope, $timeout){
  $scope.taipei = new google.maps.LatLng(25.039155, 121.549678);
  $scope.mapOption = {
    zoom: 18,
    minZoom: 8,
    maxZoom: 18,
    center: $scope.taipei
  };
  $scope.init = function(){
    $scope.map = new google.maps.Map(document.getElementById('map'), $scope.mapOption);
    return $scope.layer = new TileLayer({
      map: $scope.map,
      url: 'https://raw.githubusercontent.com/zbryikt/tile-cityusage/gh-pages/',
      bv: 'vector.json',
      opacity: 0.5
    });
  };
  return google.maps.event.addDomListener(window, 'load', function(){
    return $scope.$apply(function(){
      return $scope.init();
    });
  });
};