// Generated by LiveScript 1.2.0
var main;
main = function($scope, $timeout){
  $scope.taipei = new google.maps.LatLng(25.039155, 121.549678);
  $scope.mapOption = {
    zoom: 18,
    minZoom: 8,
    maxZoom: 18,
    center: $scope.taipei
  };
  $scope.init = function(){
    $scope.map = new google.maps.Map(document.getElementById('map'), $scope.mapOption);
    $scope.layer = new TileLayer({
      name: 'landusage',
      map: $scope.map,
      url: 'https://raw.githubusercontent.com/zbryikt/tile-cityusage/gh-pages/',
      getimg: function(z, x, y){
        return "http://maps.nlsc.gov.tw/S_Maps/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&STYLE=_null&TILEMATRIXSET=EPSG:3857&TILEMATRIX=EPSG:3857:" + z + "&FORMAT=image/png&LAYER=nURBAN&TILEROW=" + y + "&TILECOL=" + x;
      },
      bv: 'vector.json',
      opacity: 0.5,
      extend: true
    });
    return $scope.layer2 = new TileLayer({
      name: 'cityusage',
      map: $scope.map,
      url: 'http://static.foundi.info/cityusage/',
      bv: 'vector.json',
      opacity: 0.5,
      extend: true
    });
  };
  return google.maps.event.addDomListener(window, 'load', function(){
    return $scope.$apply(function(){
      return $scope.init();
    });
  });
};